'use strict';
const _c = {
	CHANCE_DOUBLE		: true,
	CHANCE_NOT_DOUBLE	: false,

	TODAY : 0,
	TOMORROW : 1,

	TAIPEI : 1,		// 台北
	TAICHUNG : 2,	// 台中
	KAOHSIUNG : 3,	// 高雄

	GIDX_WTESTWATER	: 0,
	GIDX_SUPERMAN	: 1,
	GIDX_MAGGYBAN	: 20,
	GIDX_LIULUNG	: 22,
	GIDX_YOSEITAIL	: 28,
	GIDX_FUGUAN		: 32,
	GIDX_AUSHE		: 52,
	GIDX_WTESTFIRE	: 554

};

function _init() {
	let env = process.env;

	// TosMM Linebot Keys
	_c.TOSMM_SU_GIDX = parseInt(env.TOSMM_SU_GIDX);

	_c.PORT_WATER = env.PORT_WATER;
	_c.CHANNEL_ID_WATER = env.CHANNEL_ID_WATER;
	_c.CHANNEL_SECRET_WATER = env.CHANNEL_SECRET_WATER;
	_c.CHANNEL_ACCESS_TOKEN_WATER = env.CHANNEL_ACCESS_TOKEN_WATER;

	_c.PORT_FIRE = env.PORT_FIRE;
	_c.CHANNEL_ID_FIRE = env.CHANNEL_ID_FIRE;
	_c.CHANNEL_SECRET_FIRE = env.CHANNEL_SECRET_FIRE;
	_c.CHANNEL_ACCESS_TOKEN_FIRE = env.CHANNEL_ACCESS_TOKEN_FIRE;

	_c.CLIENT_APP_USER_ID = env.CLIENT_APP_USER_ID;

	// Path of drawing cards
	_c.TOSMM_TORO_SERIES = env.TOSMM_TORO_SERIES;

	_c.TOSMM_TORO_PIC_PATH = env.TOSMM_TORO_PIC_PATH;
	_c.TOSMM_TORO_PIC_PATH_TOS = env.TOSMM_TORO_PIC_PATH_TOS;
	_c.TOSMM_TORO_PIC_PATH_TCHANCE = env.TOSMM_TORO_PIC_PATH_TCHANCE;
	_c.TOSMM_TORO_PIC_PATH_TCHANCED = env.TOSMM_TORO_PIC_PATH_TCHANCED;
	_c.TOSMM_TORO_PIC_PATH_ASA = env.TOSMM_TORO_PIC_PATH_ASA;
	_c.TOSMM_TORO_PIC_PATH_SM_ASA = env.TOSMM_TORO_PIC_PATH_SM_ASA;
	_c.TOSMM_TORO_PIC_PATH_KUZI = env.TOSMM_TORO_PIC_PATH_KUZI;
	_c.TOSMM_TORO_PIC_PATH_TEMP = env.TOSMM_TORO_PIC_PATH_TEMP;

	// Email Bug Report
	_c.BUG_REPORT_EMAIL_USER = env.BUG_REPORT_EMAIL_USER;
	_c.BUG_REPORT_EMAIL_PASSWORD = env.BUG_REPORT_EMAIL_PASSWORD;
	_c.BUG_REPORT_EMAIL_SERVER_PORT = parseInt(env.BUG_REPORT_EMAIL_SERVER_PORT);
	_c.BUG_REPORT_EMAIL_HOST = env.BUG_REPORT_EMAIL_HOST;
	_c.BUG_REPORT_EMAIL_SSL = env.BUG_REPORT_EMAIL_SSL;
	_c.BUG_REPORT_EMAIL_FROM = env.BUG_REPORT_EMAIL_FROM;
	_c.BUG_REPORT_EMAIL_TO = env.BUG_REPORT_EMAIL_TO;
	_c.BUG_REPORT_EMAIL_CC = env.BUG_REPORT_EMAIL_CC;

	// BITLY Keys - Shorten hyper-links
	_c.TOSMM_BITLY_KEY = env.TOSMM_BITLY_KEY;
	_c.TOSMM_BITLY_1_KEY = env.TOSMM_BITLY_1_KEY;
	_c.TOSMM_BITLY_2_KEY = env.TOSMM_BITLY_2_KEY;
	_c.TOSMM_BITLY_3_KEY = env.TOSMM_BITLY_3_KEY;
	_c.TOSMM_BITLY_4_KEY = env.TOSMM_BITLY_4_KEY;

	// Google Spreadsheet IDs
	_c.TOSMM_GSID_WTESTWATER = env.TOSMM_GSID_WTESTWATER;
	_c.TOSMM_GSID_SUPERMAN = env.TOSMM_GSID_SUPERMAN;
	_c.TOSMM_GSID_MAGGYBAN = env.TOSMM_GSID_MAGGYBAN;
	_c.TOSMM_GSID_LIULUNG = env.TOSMM_GSID_LIULUNG;
	_c.TOSMM_GSID_YOSEITAIL = env.TOSMM_GSID_YOSEITAIL;
	_c.TOSMM_GSID_FUGUAN = env.TOSMM_GSID_FUGUAN;
	_c.TOSMM_GSID_AUSHE = env.TOSMM_GSID_AUSHE;

	return _c;
}

//////////////  Module Exports //////////////////
module.exports = {
	init : _init
};